version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3352:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123